### ISSUE TITLE
rpc_debug is disabled by default on the local goloop chain in the e2edemo

### ISSUE THREAD

**Issue by FidelVe** [icon-project/btp2#15]
**Describe the issue**
The rpc_debug option is disabled by default on the local goloop chain in the e2edemo

Given that the e2edemo is targeted for testing this option should be enabled by default.

**Comment by sink772** [comment]
There are some [SystemConfig](https://github.com/icon-project/goloop/blob/master/doc/goloop_admin_api.md#systemconfig) in `goloop` server, which can be configured in runtime without shut-downing the node.  Enabling `v3d` RPC endpoint (i.e., `rpc_debug`) is one of those and can be enabled using the `rpcIncludeDebug` key.
```
docker compose exec icon-node goloop system config rpcIncludeDebug true
```

You can also check the current system configs via the following command.
```
$ docker compose exec icon-node goloop system info
{
  "buildVersion": "v1.3.7",
  "buildTags": "linux/amd64 tags(rocksdb)-2023-05-31-05:27:48",
  "setting": {
    "address": "hxb6b5791be0b5ef67063b3c10b840fb81514db2fd",
    "p2p": "127.0.0.1:8080",
    "p2pListen": "0.0.0.0:7080",
    "rpcAddr": ":9080",
    "rpcDump": false
  },
  "config": {
    "eeInstances": 1,
    "rpcBatchLimit": 10,
    "rpcDefaultChannel": "",
    "rpcIncludeDebug": true,
    "rpcRosetta": false,
    "wsMaxSession": 10
  }
}
```

**Comment by FidelVe** [comment]
Thanks for the reply.

I created a PR to enable this configuration by default on the node, this will make the development process easier on the developers that don't currently know how to enable this configuration but need to use the `debug_getTrace` rpc method for debugging purposes

https://github.com/icon-project/btp2/pull/20
