### ISSUE TITLE
cross chain messages using xcall not arriving on target chain

### ISSUE THREAD

**Issue by FidelVe** [icon-project/btp2#22]
**Describe the issue**
after having the local environment running for several days and making several cross chain messages there comes a point where the process of waiting for the events on the target chain to be raised fails.

basically the programs waits for blocks after blocks for the event (the CallMessage event) and it never gets raised, this makes me think the problem is with the relayer not properly relaying the cross chain transaction to the target chain.

the solution im applying so far is to rebuild everything from scratch (delete the btp folder, clone it again, deploy the contracts again etc) and continue testing xcall

**Comment by mksong-icon** [comment]
What configuration have you used for it?
ICON-to-ICON? or ICON-to-Hardhat? or else?

**Comment by FidelVe** [comment]
havent been able to reproduce this, im closing the issue, in case im able to reproduce this I will report again properly.
