### ISSUE TITLE
Sepolia to Berlin fails with insufficient fee error.

### ISSUE THREAD

**Issue by hemz10** [icon-project/btp2#23]
**Describe the issue**
Using the e2e demo script to send transaction with rollback data, transaction fails with insufficient fee, which means getFee() value returned is incorrect to make this transaction. Hence I am not able to make a successful transaction from Sepolia -> Berlin with rollback data. 

**To reproduce**
1. Modify the e2e demo to execute with testnet
2. Try Sepolia to Berlin sendCallMessage with rollback data
3. Observe
4. Transaction fails with insufficient fee. 

**Expected behavior**
fee value returned by getFee() method should be accurate to make transaction success. 

**Screenshots**
![image](https://github.com/icon-project/btp2/assets/96766939/117e2d00-3896-4e95-9e03-90374bbe3757)
![image](https://github.com/icon-project/btp2/assets/96766939/871ff350-d891-4ee6-92c5-e4e545746aab)

**System information (please complete the following information):**
 - OS: [linux]
 - Sub-program: [xcall,]

**Additional context**
I manually tried increasing the fee value but still transaction failed.
I added below values to hardhat.config.ts under networks. Only after adding this sendCallMessage without rollback data actually worked or else it's the same issue. 
 gas: 2100000,
 gasPrice: 8000000000,

**Comment by mksong-icon** [comment]
The old fee table in Sepolia is incorrect. The fee which the getFee() function returns is too large to afford in the test network. So, it will fail continuously.

We are on the way to fix the fee table.

**Comment by mksong-icon** [comment]
Fee table is updated correctly.
And please refer https://github.com/iconloop/btp2-testnet/wiki/Fee-System for setting fee.
