### ISSUE TITLE
Message Recieved evnt not indexed in explorer

### ISSUE THREAD

**Issue by shanithkk** [icon-project/btp2#24]
**Describe the issue**
sending sendCallMessage from sepolia to berlin using e2e demo script, after successful transaction the script verifies the recieved event but that isnot indexed in the explorer.

**To reproduce**
1. send message from sepolia to berlin
2. wait for event in icon chain
3. check the event in explorer also script.
4. Observed that event is not present the explorer

**Expected behavior**
All event emitted in dapp should present in the event tab in explorer

**Screenshots**
![image](https://github.com/icon-project/btp2/assets/59169878/6082ab05-362b-4272-8619-afbca23e6565)

Explorer event tab
<img width="1229" alt="image" src="https://github.com/icon-project/btp2/assets/59169878/10e0ffc8-01ed-4c36-a967-5a4c72d64f55">

Additional Information
The execute call transaction hash on xcall in icon chain [here](https://berlin.tracker.solidwallet.io/transaction/0xbdb5e54ce67e281a4ae241f989c0a22183d286d53780f397284b4075b7398695) : 0xbdb5e54ce67e281a4ae241f989c0a22183d286d53780f397284b4075b7398695

**Comment by mksong-icon** [comment]
Hmm. I can see in other tracker.
https://berlin.tracker.solidwallet.io/contract/cxf4958b242a264fc11d7d8d95f79035e35b21c1bb#events

**Comment by mksong-icon** [comment]
OK, I see that the events are not listed in **Events** of `cx14cfd59cbe77cd4d566855d40c369976b06c9f94`
https://berlin.tracker.solidwallet.io/contract/cx14cfd59cbe77cd4d566855d40c369976b06c9f94#events

**Comment by mksong-icon** [comment]
It comes from the design of the tracker, not an issue of BTP2 codes.
