### ISSUE TITLE
No Transactions recorded in BMV's even after successful cross chain transaction

### ISSUE THREAD

**Issue by hemz10** [icon-project/btp2#28]
**Describe the issue**
We have been making so many transaction recently but i see no transaction in BMV contracts. Only BSC's BMV has some transaction. testnet contract addresses from [here](https://github.com/iconloop/btp2-testnet )

**To reproduce**
Steps to reproduce the behaviour:
1. Make a successful sendCallMessage transaction 
2. Check if the messages are verified in BMV
3. Observe that there are no transactions in BMV's of Icon and Sepolia

**Expected behavior**
Messages should be verified in BMV and we should have transactions verifying the messages.

**Comment by mksong-icon** [comment]
ICON Tracker shows events of all related contracts in the first target contract.
I don't know why it's designed like that. And even if it shows events, there would be nothing in the tab because it doesn't emit any events.

**Comment by hemz10** [comment]
Yes it doesn't emit any events but there are some internal transactions happening which is being recorded in BMV of BSC for example - https://testnet.bscscan.com/address/0xfcdd2ab0d0d98c3f74db20a0913c7e3b264df8a1#internaltx

**Comment by hemz10** [comment]
Sure, here is an example transaction from Berlin to Sepolia. 
Icon - https://berlin.tracker.solidwallet.io/transaction/0xf72523195e7dde5391c2a7d8a14601678939130f55e4e908a265fa7167edab89

Sepolia - 
https://sepolia.etherscan.io/tx/0xd197dae630fb0c3288294a2bb66298946f32a80ee02296cdf2dcb00d6624b76b

Sepolia BMV - https://sepolia.etherscan.io/address/0x684ba8F34f9481f7F02aCd4F143506E11AC19E3E

**Comment by robcxyz** [comment]
Hi @hemz10 - Sorry for delay. 

I see the exact same data. 

https://tracker.berlin.icon.community/transaction/0xf72523195e7dde5391c2a7d8a14601678939130f55e4e908a265fa7167edab89
https://berlin.tracker.solidwallet.io/transaction/0xf72523195e7dde5391c2a7d8a14601678939130f55e4e908a265fa7167edab89

Am I missing something?

**Comment by CyrusVorwald** [comment]
@hemz10 can you share a tx where Berlin is the destination chain?

The bmv is only used on the destination

**Comment by hemz10** [comment]
> Hi @hemz10 - Sorry for delay.
> 
> I see the exact same data.
> 
> https://tracker.berlin.icon.community/transaction/0xf72523195e7dde5391c2a7d8a14601678939130f55e4e908a265fa7167edab89 https://berlin.tracker.solidwallet.io/transaction/0xf72523195e7dde5391c2a7d8a14601678939130f55e4e908a265fa7167edab89
> 
> Am I missing something?

h

**Comment by hemz10** [comment]
> Hi @hemz10 - Sorry for delay.
> 
> I see the exact same data.
> 
> https://tracker.berlin.icon.community/transaction/0xf72523195e7dde5391c2a7d8a14601678939130f55e4e908a265fa7167edab89 https://berlin.tracker.solidwallet.io/transaction/0xf72523195e7dde5391c2a7d8a14601678939130f55e4e908a265fa7167edab89
> 
> Am I missing something?

Hi @robcxyz 
Yes the transaction hash I shared you is successful transaction from Berlin to Sepolia. Issue I reported was that in destination BMV there is no transaction recorded. In this case BMV of Sepolia has no transaction. 
Sepolia BMV -  https://sepolia.etherscan.io/address/0x684ba8F34f9481f7F02aCd4F143506E11AC19E3E

**Comment by hemz10** [comment]
> 

Hi @CyrusVorwald ,
Sure here is a transaction from Sepolia to Berlin. 
Source Sepolia sendCallMessage Hash - https://sepolia.etherscan.io/tx/0xc143dada5c5a5b8c9f512fb054168ddddf53d7fed648886a8df4ba5ae27cbcd3

Destination Berlin executeCall Hash - 
https://berlin.tracker.solidwallet.io/transaction/0x17b99b5c2276f6527c38021ed54492170379ba97db62a88fe37987cbebebab74

And this destination Icon eth2 BMV - 
https://berlin.tracker.solidwallet.io/contract/cxbab382c24c5e492d45cf11c0b07fd36e8344e96f#transactions

**Comment by mksong-icon** [comment]
It's not an issue in BTP, but is about the tracker.
So, if you need to register it to the tracker (https://github.com/sudoblockio/icon-tracker).
