### ISSUE TITLE
Partial Message scenario from Berlin to Sepolia fails in testnet

### ISSUE THREAD

**Issue by hemz10** [icon-project/btp2#38]
**Describe the issue**
Make a transaction from Dapp that can send partial message, transaction fails irrespective of increasing the fee. But the same Dapp is able send a partial message transaction and compile them in the destination as full message. 

**To reproduce**
1. Make a transaction from the Dapp with _type as 1 where 1 means partial message type
2. Transaction fails. 

**Expected behavior**
When the transaction is successful in localnet, the same transaction should work in testnet too.  

**Additional context**
You can find failed transactions here - https://berlin.tracker.solidwallet.io/contract/cx32896280b64f564f929e48c644bd8e1088a75819
Dapp Address :
Icon - cx32896280b64f564f929e48c644bd8e1088a75819
Sepolia - 0x6c68227077B4A79A5274d7fD3f106697CD8247d0

**Comment by sink772** [comment]
It seems you are trying to invoke multiple `sendCallMessage` from your DApp, but it has a bug in the logic to set the proper fees.
Your DApp set all the fees for the first partial message, so it caused the OufOfBalance error when the DApp tried to send a subsequent message since there was no remained balance in your DApp contract.

```
FRAME[2] CALL start from=cx32896280b64f564f929e48c644bd8e1088a75819 to=cxf4958b242a264fc11d7d8d95f79035e35b21c1bb value=50000000000000000000 steplimit=2498629882 dataType=call data={"method":"sendCallMessage","params":["btp://0xaa36a7.eth2/0x6c68227077B4A79A5274d7fD3f106697CD8247d0","0xcb028720746f20746573010b",null]}
FRAME[7] START parent=FRAME[2]
FRAME[7] INVOKE start score=cxf4958b242a264fc11d7d8d95f79035e35b21c1bb method=sendCallMessage
FRAME[7] STEP apply type=contractCall count=1 cost=25000 total=25000
FRAME[7] INVOKE done status=OutOfBalance msg=E0011:OutOfBalance steps=25000
FRAME[7] END success=false steps=25000
FRAME[2] CALL done status=OutOfBalance steps=25000 msg=OutOfBalance
```

**Comment by Sid-hugobyte** [comment]
This issue has been resolved
